image:
  # -- image repository
  repository: tccr.io/truecharts/booksonic-air
  # -- image pull policy
  pullPolicy: IfNotPresent
  # -- image tag
  tag: v2009.1.0@sha256:82747a170977685e837f4ec76d196e4a7d435371d0a4af7c7527a6bbc745e307

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

# See more environment variables in the [booksonic-air documentation](https://github.com/linuxserver/docker-booksonic-air#parameters)
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC
  # -- Specify the user ID the application will run as
  PUID: 568
  # -- Used to set the base path for reverse proxies eg. /booksonic, /books, etc.
  # CONTEXT_PATH=url-base

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      main:
        port: 10048
        targetPort: 4040

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    mountPath: "/config"
