image:
  # -- image repository
  repository: tccr.io/truecharts/hyperion.ng
  # -- image tag
  tag: v2.0.12@sha256:90359e89c5a97fbf5ad3debf42d485d707eb7186664288ccfad100c325848a5d
  # -- image pull policy
  pullPolicy: IfNotPresent

securityContext:
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

# -- environment variables. See [image docs](https://docs.linuxserver.io/images/docker-airsonic#environment-variables-e) for more details.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC
  # -- Specify the user ID the application will run as
  PUID: 568

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      main:
        port: 10065
        targetPort: 8090
  jsonservice:
    enabled: true
    ports:
      jsonservice:
        enabled: true
        port: 19444
        targetPort: 19444
  protobufservice:
    enabled: true
    ports:
      protobufservice:
        enabled: true
        port: 19445
        targetPort: 19445
  boblightservice:
    enabled: true
    ports:
      boblightservice:
        enabled: true
        port: 19333
        targetPort: 19333

persistence:
  config:
    enabled: true
    mountPath: "/root/.hyperion"
