image:
  repository: tccr.io/truecharts/esphome
  pullPolicy: IfNotPresent
  tag: v2021.12.0@sha256:ac5a972431f16f8fc194e80904c77862c6570498a553cd12bc5f7dbfd4f0cce9

service:
  main:
    ports:
      main:
        port: 6052
        targetPort: 6052

env: {}
  # ESPHOME_DASHBOARD_USE_PING: true
  # ESPHOME_DASHBOARD_RELATIVE_URL: "/"
  # ESPHOME_QUICKWIZARD:
  # ESPHOME_IS_HASSIO:
  # DISABLE_HA_AUTHENTICATION:
  # USERNAME:
  # PASSWORD:

persistence:
  config:
    enabled: true
    mountPath: "/config"
