image:
  repository: tccr.io/truecharts/babybuddy
  pullPolicy: IfNotPresent
  tag: v1.9.2@sha256:776a2f9571321b752dcd0d7dd107c5563806f0dde8689674303f7b190dc96b8c

# See more environment variables in the babybuddy documentation
# https://github.com/linuxserver/docker-babybuddy#parameters
env: {}
  # TZ:

envTpl:
  DB_ENGINE: "django.db.backends.postgresql"
  DB_NAME: "{{ .Values.postgresql.postgresqlDatabase }}"
  DB_USER: "{{ .Values.postgresql.postgresqlUsername }}"
  DB_PORT: "5432"

envValueFrom:
  DB_PASSWORD:
    secretKeyRef:
      name: dbcreds
      key: postgresql-password
  DB_HOST:
    secretKeyRef:
      name: dbcreds
      key: plainhost

securityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: true
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10069
        targetPort: 8000

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

# Enabled postgres
postgresql:
  enabled: true
  existingSecret: "dbcreds"
  postgresqlUsername: babybuddy
  postgresqlDatabase: babybuddy
