image:
  repository: tccr.io/truecharts/jackett
  pullPolicy: IfNotPresent
  tag: v0.20.147@sha256:40944fe8ca0d946c399a5f63691bbb2be482c2704d99535db397af100a3d0527

securityContext:
  readOnlyRootFilesystem: false

service:
  main:
    protocol: HTTP
    ports:
      main:
        targetPort: 9117
        port: 9117

probes:
  liveness:
    path: "/UI/Login"

  readiness:
    path: "/UI/Login"

  startup:
    path: "/UI/Login"

env: {}
  # TZ: UTC
  # PUID: 1001
persistence:
  config:
    enabled: true
    mountPath: "/config"
