image:
  repository: tccr.io/truecharts/qbittorrent
  pullPolicy: IfNotPresent
  tag: v4.3.9@sha256:6508ca6bd05d003d92852d5bd8deaae3176d776a5789ad68199ba1807d43cf8c

securityContext:
  readOnlyRootFilesystem: false

env: {}
    # TZ: UTC
  # PUID: 1001

service:
  main:
    ports:
      main:
        port: 10095
        targetPort: 8080
  torrent:
    enabled: true
    ports:
      torrent:
        enabled: true
        port: 6881
        targetPort: 6881
  torrentudp:
    enabled: true
    ports:
      torrentudp:
        enabled: true
        port: 6881
        targetPort: 6881
        protocol: UDP

persistence:
  config:
    enabled: true
    mountPath: "/config"


additionalVolumes:
  - name: qbittorrent-scripts
    emptyDir: {}
    ## When you want to enable automatic port configuration at startup, adjust this to:
    # configMap:
    #   name: <RELEASENAME>-scripts
    #   defaultMode: 511

additionalVolumeMounts:
  - mountPath: "/config/custom-cont-init.d"
    name: qbittorrent-scripts
