#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/charts/tree/master/charts/common/values.yaml
#

image:
  repository: jgeusebroek/spotweb
  pullPolicy: IfNotPresent
  tag: 20210328@sha256:e41482a844d8e5582239868d61ef8335dba156fa39d3f1c8ddc762ab214cf5b9

# See more environment variables in the ${CHARTNAME} documentation
# https://${CHARTNAME}.org/docs
env: {}
  # TZ:

service:
  port:
    port: 1880

ingress:
  enabled: false

# persistence:
#   data:
#     enabled: false
#     emptyDir: false
#     mountPath: /data
