image:
  repository: tccr.io/truecharts/gotify-server
  pullPolicy: IfNotPresent
  tag: v2.1.3@sha256:832ee2e12000da56c5778813dd69b60694dcfcea853afac684f12402c89295f4

secret:
  user: "admin"
  pass: "admin"

# See more environment variables in the gotify documentation
# https://gotify.net/docs/config#environment-variables
env:
  # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  TZ: "America/Los_Angeles"
  GOTIFY_SERVER_PORT: 8080
  GOTIFY_SERVER_KEEPALIVEPERIODSECONDS: 0
  GOTIFY_SERVER_LISTENADDR: ""
  GOTIFY_SERVER_SSL_ENABLED: false
  # lists are a little weird but do-able (:
  # GOTIFY_SERVER_SSL_LETSENCRYPT_HOSTS: "- mydomain.tld\n- myotherdomain.tld"
  GOTIFY_SERVER_RESPONSEHEADERS: "X-Custom-Header: \"custom value\""
  # GOTIFY_SERVER_CORS_ALLOWORIGINS: "- \".+.example.com\"\n- \"otherdomain.com\""
  # GOTIFY_SERVER_CORS_ALLOWMETHODS: "- \"GET\"\n- \"POST\""
  # GOTIFY_SERVER_CORS_ALLOWHEADERS: "- \"Authorization\"\n- \"content-type\""
  # GOTIFY_SERVER_STREAM_ALLOWEDORIGINS: "- \".+.example.com\"\n- \"otherdomain.com\""
  GOTIFY_SERVER_STREAM_PINGPERIODSECONDS: 45
  GOTIFY_PASSSTRENGTH: 10
  GOTIFY_UPLOADEDIMAGESDIR: "data/images"
  GOTIFY_PLUGINSDIR: "data/plugins"

envFrom:
  - configMapRef:
      name: gotifyenv

service:
  main:
    ports:
      main:
        port: 10084
        targetPort: 8080

persistence:
  data:
    enabled: true
    mountPath: "/app/data"

# Enabled postgres
postgresql:
  enabled: true
  existingSecret: "dbcreds"
  postgresqlUsername: gotify
  postgresqlDatabase: gotify
