image:
  repository: tccr.io/truecharts/kms
  pullPolicy: IfNotPresent
  tag: vminimal@sha256:8f6b1deff8e6358d2f1201a6080288382f49dc959ee7ba0ba0cbba9049de7fff

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 1688
        targetPort: 1688
