image:
  repository: tccr.io/truecharts/lychee-laravel
  pullPolicy: IfNotPresent
  tag: v4.3.6@sha256:34d3e89ab62184efaeed53cc4fffca468c92febfa49ef3d1da971fd0aef34e7d

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10017
        targetPort: 80

env: {}
  # PHP_TZ: UTC
  # PUID: 1001
persistence:
  config:
    enabled: true
    mountPath: "/config"
