image:
  repository: tccr.io/truecharts/collabora
  tag: v6.4.14.3@sha256:95b1bba1e26633586c9f49cc94602237d21a09a4a7e7059ac807927d3b15a293
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: true
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 104
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10105
        targetPort: 9980
secret:
  username: admin
  password: changeme
env:
  domain: nextcloud\.domain\.tld
  dictionaries: de_DE en_GB en_US es_ES fr_FR it nl pt_BR pt_PT ru
  extra_params: "-o:welcome.enable=false -o:user_interface.mode=notebookbar -o:ssl.termination=true -o:ssl.enable=false"
  server_name: collabora\.domain\.tld
