apiVersion: v2
appVersion: "0.11.0"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.18
description: An organizer for your porn, written in Go
home: https://github.com/truechartsapps/tree/master/charts/stable/stash
icon: https://raw.githubusercontent.com/stashapp/website/master/images/stash.svg
keywords:
- porn
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: stash
sources:
- https://github.com/stashapp/stash
- https://hub.docker.com/r/stashapp/stash
version: 5.0.1
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
