image:
  repository: tccr.io/truecharts/gaps
  pullPolicy: IfNotPresent
  tag: v0.8.8@sha256:76d297b1431aa14c7643d0e8b0c91167cdb3ac35efa978c32162482ed03ccd73

securityContext:
  readOnlyRootFilesystem: false

service:
  main:
    ports:
      main:
        port: 8484
        targetPort: 8484

env: {}
  # TZ: UTC

persistence:
  data:
    enabled: true
    mountPath: "/usr/data"
