image:
  repository: tccr.io/truecharts/code-server
  pullPolicy: IfNotPresent
  tag: v3.12.0@sha256:b2132ab84a76b799dca995c90d4eb5765f13267408f795541bec670ff22cce38

args:
  - --user-data-dir
  - "/config/.vscode"
  - --auth
  - none

env: {}
  # PROXY_DOMAIN: code-server.my.domain

securityContext:
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: true

service:
  main:
    ports:
      main:
        port: 10063
        targetPort: 8080

persistence:
  config:
    enabled: true
    mountPath: "/config"
