image:
  # -- image repository
  repository: tccr.io/truecharts/octoprint
  # -- image tag
  tag: v1.7.2@sha256:d9db81d173df140c4e018965ebafba9be5f58a83f40e1c489210220627a13d24
  # -- image pull policy
  pullPolicy: IfNotPresent

securityContext:
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

# -- environment variables.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC
  # -- Enable MJPG Streamer
  # Enable this to ensure camera streaming is enabled you add a video device.
  ENABLE_MJPG_STREAMER: "true"
  # -- MJPG Streamer input parameters
  MJPG_STREAMER_INPUT:  # "-y -n -r 640x480"
  # -- MJPG Streamer camera device
  CAMERA_DEV:  # /dev/video0

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      main:
        port: 10021
        targetPort: 80

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  data:
    enabled: true
    mountPath: "/octoprint"
  # -- Configure a hostPathMount to mount a USB device in the container.
  # @default -- See values.yaml
  varrun:
    enabled: true
