image:
  # -- image repository
  repository: tccr.io/truecharts/komga
  # -- image tag
  tag: v0.135.0@sha256:6d5dcf093464493c4490b8b809f45b908302b0143af60d30e4322e2aa8654851
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See more environment variables in the [komga documentation](https://komga.org/installation/configuration.html#optional-configuration).
# @default -- See below
env: {}

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      main:
        port: 10085
        targetPort: 8080

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    mountPath: "/config"
  data:
    enabled: true
    mountPath: "/data"
