image:
  # -- image repository
  repository: tccr.io/truecharts/deconz
    # -- image tag
  tag: v2.13.01@sha256:f43bf475d9d0cf6bc0700da1b10d5533e1eaea43f1a417a096ad8cafb033b249
  # -- image pull policy
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

secret:
  DECONZ_VNC_PASSWORD: ""

# -- environment variables. See [image docs](https://github.com/marthoc/docker-deconz/blob/master/README.md) for more details.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC
  # -- Override the location where deCONZ looks for the RaspBee/Conbee device.
  DECONZ_DEVICE:  # /dev/ttyUSB0
  # -- Enable VNC access to the container to view the deCONZ ZigBee mesh
  DECONZ_VNC_MODE: 1
  # -- Web UI listen port
  DECONZ_WEB_PORT: 8080
  # -- Websocket listen port
  DECONZ_WS_PORT: 6080
  # -- VNC server listen port
  DECONZ_VNC_PORT: 5900
  DECONZ_UID: 568
  DECONZ_GID: 568

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      main:
        port: 10008
        targetPort: 8080
  websocket:
    enabled: true
    ports:
      websocket:
        enabled: true
        port: 10001
        targetPort: 6080
  vnc:
    enabled: true
    ports:
      vnc:
        enabled: true
        port: 10002
        targetPort: 5900

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    mountPath: "/opt/deCONZ"

# -- Affinity constraint rules to place the Pod on a specific node.
# [[ref]](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity)
affinity: {}
#   nodeAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: app
#           operator: In
#           values:
#           - zigbee-controller
