image:
  repository: ghcr.io/truecharts/memcached
  pullPolicy: IfNotPresent
  tag: v1.6.12@sha256:3887a722b71d004c54ecf41a9f937edf5cd6a85c5e7c70935964b7aedf61b856

service:
  main:
    ports:
      main:
        port: 11211
        targetPort: 11211
