image:
  repository: tccr.io/truecharts/unifi
  tag: v6.5.54@sha256:b001bbeb9daf75840bf7068748c75279e043e841d2547cd0137e5f9b8bc714d3
  pullPolicy: IfNotPresent

envTpl:
  # Permissions Settings
  UNIFI_GID: "{{ .Values.env.PUID }}"
  UNIFI_UID: "{{ .Values.podSecurityContext.fsGroup }}"

service:
  main:
    ports:
      main:
        protocol: HTTPS
        port: 8443
        targetPort: 8443
  comm:
    enabled: true
    ports:
      comm:
        enabled: true
        port: 8080
        targetPort: 8080
  stun:
    enabled: true
    ports:
      stun:
        enabled: true
        port: 3478
        targetPort: 3478
        protocol: UDP
  speedtest:
    enabled: true
    ports:
      speedtest:
        enabled: true
        port: 6789
        targetPort: 6789
  guestportal:
    enabled: true
    ports:
      web:
        enabled: true
        port: 8880
        targetPort: 8880
        protocol: HTTP
      websecure:
        enabled: true
        port: 8843
        targetPort: 8843
        protocol: HTTPS

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0

env:
  # TZ:
  PUID: 568
persistence:
  config:
    enabled: true
    mountPath: "/unifi"
