image:
  repository: tccr.io/truecharts/friendica
  pullPolicy: IfNotPresent
  tag: v2021.09@sha256:5af8766837016690d589a928e800ebd67718a348822e3ecb31e24b45bb6cf8a0

securityContext:
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

# See more environment variables in the friendica documentation
# https://hub.docker.com/_/friendica
env:
  MYSQL_USER: friendica
  MYSQL_DATABASE: friendica

service:
  main:
    ports:
      main:
        port: 10058
        targetPort: 80

persistence:
  varrun:
    enabled: true
  config:
    enabled: true
    mountPath: /var/www/html

envValueFrom:
  MYSQL_HOST:
    secretKeyRef:
      name: mariadbcreds
      key: plainhost
  MYSQL_PASSWORD:
    secretKeyRef:
      name: mariadbcreds
      key: mariadb-password
  REDIS_HOST:
    secretKeyRef:
      name: rediscreds
      key: plainhost
  REDIS_PW:
    secretKeyRef:
      name: rediscreds
      key: redis-password

redis:
  enabled: true
  existingSecret: "rediscreds"

mariadb:
  enabled: true
  mariadbUsername: friendica
  mariadbDatabase: friendica
  existingSecret: "mariadbcreds"
