image:
  # -- image repository
  repository: tccr.io/truecharts/documentserver
  # -- image tag
  tag: v6.4.2.6@sha256:c298cbb59a2d7f73a5a9bc5cc11f9e0e299ef2ab966e64f3e8d8382921a6341c
  # -- image pull policy
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

secret:
  JWT_SECRET: "randomgeneratedstring"
# -- environment variables. See [image docs](https://github.com/ONLYOFFICE/Docker-DocumentServer#available-configuration-parameters) for more details.
env:
  WOPI_ENABLED: true
  JWT_ENABLED: true
service:
  main:
    ports:
      main:
        port: 10043
        targetPort: 80

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false
