name: "Docs: Deploy"
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - '.github/workflows/docs.deploy.yaml'
      - 'mkdocs.yml'

jobs:
  build:
    name: Deploy Wiki
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2
        with:
          token: ${{ secrets.BOT_TOKEN }}

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          REQUIREMENTS: docs/requirements.txt
