name: "Prune Old Releases"

on:
  workflow_dispatch:

jobs:
  housekeeping:
    runs-on: ubuntu-latest
    name: "prune old releases"
    steps:
    - name: Checkout
      uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2
      with:
        fetch-depth: 0
    - uses: actions/delete-package-versions@fc4c9fe9124691791f1856863589939fd5a1c071 # renovate: tag=v2
      with:
        min-versions-to-keep: 200
